# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wFmQIUlhinA_mBDxEj4AVHrqbynLTpCI
"""

from fastapi import FastAPI, File, UploadFile
import torch
import torch.nn as nn
from torchvision import transforms
from PIL import Image
import io
from fastapi.middleware.cors import CORSmiddleware
app=FASTAPI(title="MNIST CNN API ")

app.add_middleware(
    CORSmiddleware,
    allow_origin=["*"],
    allow_credentials=True,
    allow_methods=['*'],
    allow_header=['*'],
)
app = FastAPI()

# Device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Same CNN model (IMPORTANT: must match training)
class CNN(nn.Module):
    def __init__(self):
        super(CNN, self).__init__()

        self.conv1 = nn.Conv2d(1, 32, kernel_size=3)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3)

        self.fc1 = nn.Linear(64 * 5 * 5, 128)
        self.fc2 = nn.Linear(128, 10)

        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(0.25)

    def forward(self, x):
        x = self.pool(self.relu(self.conv1(x)))
        x = self.pool(self.relu(self.conv2(x)))

        x = x.view(-1, 64 * 5 * 5)
        x = self.dropout(self.relu(self.fc1(x)))
        x = self.fc2(x)

        return x

# Load model (choose one option)

# Option 1: Load full model
# model = torch.load("mnist_cnn_full_model.pth", map_location=device)

# Option 2: Load weights (recommended)
model = CNN().to(device)
model.load_state_dict(torch.load("mnist_cnn_weights.pth", map_location=device))

model.eval()

# Transform (same as training)
transform = transforms.Compose([
    transforms.Grayscale(),
    transforms.Resize((28, 28)),
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])

@app.get("/")
def home():
    return {"message": "MNIST CNN FastAPI is running 🚀"}

@app.post("/predict/")
async def predict(file: UploadFile = File(...)):
    # Read image
    image_bytes = await file.read()
    image = Image.open(io.BytesIO(image_bytes)).convert("L")

    # Preprocess
    image = transform(image).unsqueeze(0).to(device)

    # Prediction
    with torch.no_grad():
        outputs = model(image)
        _, predicted = torch.max(outputs, 1)

    return {"prediction": int(predicted.item())}